#!/usr/bin/env php
<?php
/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| First we need to get an application instance. This creates an instance
| of the application / container and bootstraps the application so it
| is ready to receive HTTP / Console requests from the environment.
|
*/
$app = require __DIR__.'/../bootstrap/app.php';
/*
|--------------------------------------------------------------------------
| Run The Application
|--------------------------------------------------------------------------
|
| Once we have the application, we can handle the incoming request
| through the kernel, and send the associated response back to
| the client's browser allowing them to enjoy the creative
| and wonderful application we have prepared for them.
|
*/
assert($app instanceof \Swooen\Application);

$factory = new \Swooen\Runtime\Swoole\WebSocket\WsJsonConnectionFactory('0.0.0.0', 8080);
$app->instance(\Swooen\Communication\ConnectionFactory::class, $factory);
$app->bind(\Swooen\Communication\Route\Loader\RouteLoader::class, function() {
    return new \Swooen\Communication\Route\Loader\PHPFileLoader(
        __DIR__.'/../routes/v1.php'
    );
});
$app->run();
